### ISSUE TITLE
Change badge icon if active tab is duplicate?

### ISSUE THREAD

**Issue by orschiro** [VDSnuff/KillClonesTabs#4]
Hey there, 

Came across your extension and love it! :-)

One idea:

Would it be possible for the badge icon to change if currently active tab is a duplicate?

Would be super helpful! :-)

Thanks

**Comment by VDSnuff** [comment]
Hi Robert,

Yes sure I will do this, it's a great idea!

Thank you for your comment!

**Comment by orschiro** [comment]
Thanks so much for your openness to my feedback! Can you let me know when I
can test this feature and give my feedback? :)

**Comment by VDSnuff** [comment]
Hello Robert,

Please check the new version.
Now we indicate when we have the duplicate tabs using red extension icon.
Waiting for your feedback, and thank you for your attention!

![image](https://user-images.githubusercontent.com/16888329/38175759-d823c484-35e1-11e8-87b3-3201d71f1223.png)

**Comment by orschiro** [comment]
Happy Easter! Almost perfect. 

Check this: https://youtu.be/B1loqj3_eGM

:-)

**Comment by VDSnuff** [comment]
Hi,

Happy Holiday to you too!

The implementation of this idea was to indicate whenever we have the duplicates, so the user can see that he have redundant tabs and then with "Show duplicates" function easily found these tabs. 

For me more important to know that I have the useless stuff in my browser, so then I just can easily close it with "Kill duplicates" function.

What do you think about this?

**Comment by orschiro** [comment]
> What do you think about this?

Understand. Let me test this and get back to you! :-)

**Comment by orschiro** [comment]
@VDSnuff like it, let's keep as is. Thanks for this addition! :-)
